### ISSUE TITLE
Rejects with "Permission Denied"

### ISSUE THREAD

**Issue by shounakdatta** [mozey/run-as-admin#2]
I got the go rsrc package.
Ran `rsrc -manifest app.exe.manifest -o app.syso `.
Ran `GOOS="windows" GOARCH="386" go build -o app.exe `

Output: `bash: ./app.exe: Permission denied`

**Comment by mozey** [comment]
You probably don't have write permission on the output dir for app.exe? Try this
```
chmod u+w ./
```

Then run the build command again

**Comment by shounakdatta** [comment]
Still not working unfortunately 😢 
![image](https://user-images.githubusercontent.com/33079683/78625971-66c89580-785b-11ea-9a1f-e0b8c76c706a.png)
